/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ITManagement;

import javax.swing.JOptionPane;

/**
 *
 * @author sanskruti
 */
public class AddDevice extends javax.swing.JPanel {
   private ITworkarea itWorkarea;  
    /**
     * Creates new form AddDevice
     */
     public AddDevice(ITworkarea itWorkarea) {
        this.itWorkarea = itWorkarea;  // Set the reference of ITworkarea
        initComponents();
    }
     
     
     private void btnAddDeviceActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String deviceName = txtDeviceName.getText();
            String technician = jTextField3.getText();
            String status = txtStatus.getText();
            
            if (deviceName.isEmpty() || technician.isEmpty() || status.isEmpty()) {
                JOptionPane.showMessageDialog(this, "All fields must be filled in!");
                return;
            }

            // Get next available device ID based on current table rows
            int deviceId = Integer.parseInt(txtDeviceID.getText());

            // Add the device to the ITworkarea table
         //   itWorkarea.addDeviceToTable(deviceId, deviceName, technician, status);

            // Close the AddDevice window
            JOptionPane.showMessageDialog(this, "Device added successfully!");
            clearFields();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
private void clearFields() {
        txtDeviceID.setText("");
        txtDeviceName.setText("");
        jTextField3.setText("");
        txtStatus.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDeviceInfo = new javax.swing.JLabel();
        lblDeviceID = new javax.swing.JLabel();
        txtDeviceID = new javax.swing.JTextField();
        lblDeviceName = new javax.swing.JLabel();
        txtDeviceName = new javax.swing.JTextField();
        lblAssignedTechnician = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();

        lblDeviceInfo.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblDeviceInfo.setText("Device Infomation");

        lblDeviceID.setText("DeviceID: ");

        lblDeviceName.setText("Device Name: ");

        lblAssignedTechnician.setText("Assigned Technician: ");

        lblStatus.setText("Status:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(lblDeviceInfo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAssignedTechnician)
                            .addComponent(lblDeviceID)
                            .addComponent(lblDeviceName)
                            .addComponent(lblStatus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDeviceID, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(txtDeviceName)
                            .addComponent(jTextField3)
                            .addComponent(txtStatus))))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblDeviceInfo)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeviceID)
                    .addComponent(txtDeviceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeviceName)
                    .addComponent(txtDeviceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAssignedTechnician)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus))
                .addContainerGap(128, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblAssignedTechnician;
    private javax.swing.JLabel lblDeviceID;
    private javax.swing.JLabel lblDeviceInfo;
    private javax.swing.JLabel lblDeviceName;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtDeviceID;
    private javax.swing.JTextField txtDeviceName;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
