/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.ITManagement;

import EmergencySystem.Emergency.Emergency;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanskruti
 */
public class ITworkarea extends javax.swing.JPanel {

    /**
     * Creates new form ITworkarea
     */
    public ITworkarea() {
        initComponents();
        populateTable();
    }

    private void populateTable() {
    // Create a DefaultTableModel
    DefaultTableModel model = (DefaultTableModel) emergencyTable.getModel();
    
    // Add hardcoded device data
    model.addRow(new Object[] {1, "Laptop", "John Doe", "Pending"});
    model.addRow(new Object[] {2, "Printer", "Jane Smith", "In Progress"});
    model.addRow(new Object[] {3, "Monitor", "Alice Johnson", "Fixed"});
    model.addRow(new Object[] {4, "Router", "Bob Brown", "Pending"});
    model.addRow(new Object[] {5, "Server", "Charlie Green", "In Progress"});
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        emergencyTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAdddevice = new javax.swing.JButton();
        btnDeleteDevice = new javax.swing.JButton();

        emergencyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DeviceID", "DeviceName", "Assigned Technician", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(emergencyTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("IT Support Work Area");

        btnAdddevice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAdddevice.setText("Add Device");
        btnAdddevice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdddeviceActionPerformed(evt);
            }
        });

        btnDeleteDevice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnDeleteDevice.setText("Delete Device");
        btnDeleteDevice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteDeviceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdddevice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDeleteDevice))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteDevice)
                    .addComponent(btnAdddevice))
                .addGap(209, 209, 209))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdddeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdddeviceActionPerformed
    String deviceName = JOptionPane.showInputDialog(this, "Enter Device Name:");
        if (deviceName != null && !deviceName.trim().isEmpty()) {
            String technician = JOptionPane.showInputDialog(this, "Enter Technician Name:");
            if (technician != null && !technician.trim().isEmpty()) {
                // Set a default status for the new device (e.g., Pending)
                String status = "Pending";

                // Add the new device to the table
                DefaultTableModel model = (DefaultTableModel) emergencyTable.getModel();
                int deviceId = model.getRowCount() + 1; // Automatically assign the next available ID

                model.addRow(new Object[] {deviceId, deviceName, technician, status});

                JOptionPane.showMessageDialog(this, "Device added successfully.");
            } else {
                JOptionPane.showMessageDialog(this, "Technician name cannot be empty.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Device name cannot be empty.");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdddeviceActionPerformed

    private void btnDeleteDeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteDeviceActionPerformed
     int rowSelected = emergencyTable.getSelectedRow();

        // Check if a row is selected
        if (rowSelected >= 0) {
            // Confirm with the user before deleting
            int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete this device?",
                "Delete Device",
                JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                // Remove the selected row from the table
                DefaultTableModel model = (DefaultTableModel) emergencyTable.getModel();
                model.removeRow(rowSelected);

                JOptionPane.showMessageDialog(this, "Device deleted successfully.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Choose a device from the table to delete.");
        }                                           
      // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteDeviceActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdddevice;
    private javax.swing.JButton btnDeleteDevice;
    private javax.swing.JTable emergencyTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}


