/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.DisasterManagement;

import ui.Hospital.*;
import EmergencySystem.Emergency.Emergency;
import EmergencySystem.EmergencySystem;
import EmergencySystem.Enterprise.Enterprise;
import EmergencySystem.Network.Network;
import Hospital.Hospital;
import Hospital.UserAccount.UserAccount;
import Hospital.WorkQueue.Emergency911DepartmentWorkRequest;
import Hospital.WorkQueue.WorkRequest;
import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;
import java.awt.BorderLayout;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Komal
 */
public class FireBrigadeWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form AmbulanceWorkArea
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private EmergencySystem system;
    private Network network;
    private Emergency emergency;
    private Hospital hospital;
    public FireBrigadeWorkArea(JPanel userProcessContainer, UserAccount account, EmergencySystem system, Network network, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.system=system;
        this.network=network;
        this.hospital=(Hospital)enterprise;
        populateWorkRequestTable();
            
        
    }
    
    public void populateWorkRequestTable()
    {
        
       DefaultTableModel model = (DefaultTableModel) emergencyTable.getModel();
        
        model.setRowCount(0);
        
        for (WorkRequest workRequest:account.getWorkQueue().getWorkRequestList())
        {
            Object[] row = new Object[4];

            row[0]=  ((Emergency911DepartmentWorkRequest) workRequest);
            row[1]=  ((Emergency911DepartmentWorkRequest) workRequest).getEmergency();
            
            row[2] = hospital.getTimeTakenToReachTheAccidentLoc();
            row[3] = ((Emergency911DepartmentWorkRequest) workRequest).getEmergency().getDescription();
           
            model.addRow(row);
       }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        emergencyTable = new javax.swing.JTable();
        startJourneyBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Fire Brigade Work Area");

        emergencyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sender", "Location of emergency", "Time to reach location(in mins)", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(emergencyTable);
        if (emergencyTable.getColumnModel().getColumnCount() > 0) {
            emergencyTable.getColumnModel().getColumn(0).setMinWidth(100);
            emergencyTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            emergencyTable.getColumnModel().getColumn(0).setMaxWidth(100);
            emergencyTable.getColumnModel().getColumn(1).setMinWidth(350);
            emergencyTable.getColumnModel().getColumn(1).setPreferredWidth(350);
            emergencyTable.getColumnModel().getColumn(1).setMaxWidth(350);
            emergencyTable.getColumnModel().getColumn(3).setMinWidth(120);
            emergencyTable.getColumnModel().getColumn(3).setPreferredWidth(120);
            emergencyTable.getColumnModel().getColumn(3).setMaxWidth(120);
        }

        startJourneyBtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        startJourneyBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Hospital/images/1449794518_footprint.png"))); // NOI18N
        startJourneyBtn.setText("Start the journey");
        startJourneyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startJourneyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 749, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(startJourneyBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(startJourneyBtn)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startJourneyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startJourneyBtnActionPerformed
        // TODO add your handling code here:
        int rowSelected=emergencyTable.getSelectedRow();
        if(rowSelected>=0)
        {
            emergency=(Emergency) emergencyTable.getValueAt(rowSelected, 1);
            emergency.setEmergencyStatus("Ambulance proceeding towards the location");
//            emergency.setTimeForTheAmbulanceToReachTheAccidentalLocation(hospital.getTimeTakenToReachTheAccidentLoc());
//            Date d=new Date();
//            emergency.setReolvedTime(d);
//            emergency.setTotalTime((emergency.getReolvedTime().getTime()-emergency.getReportedTime().getTime())/1000%60);
            JOptionPane.showMessageDialog(this, "The ambulance has been departed and will reach the destination in approximately 15 minutes");
        }
        
        else
        {
            JOptionPane.showMessageDialog(this,"Choose an emergency from the table");
        }
    }//GEN-LAST:event_startJourneyBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable emergencyTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton startJourneyBtn;
    // End of variables declaration//GEN-END:variables
}
